TokenManager:
  bilibili:
    headers:
      'accept-language': zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
      'origin': https://www.bilibili.com
      'referer': https://www.bilibili.com/
      'origin_2': https://space.bilibili.com
      'cookie': buvid3=04DCFC29-2E5F-A739-895E-0653CF778B1763212infoc; b_nut=1777808963; home_feed_column=5; browser_resolution=1731-1325; buvid4=F59B0D3E-AB49-6970-F57B-5D8B48D775EE63848-026050319-SGOYUsGoYW%2BuGL5lmGG87g%3D%3D; bili_ticket=eyJhbGciOiJIUzI1NiIsImtpZCI6InMwMyIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzgwNjgxNjMsImlhdCI6MTc3NzgwODkwMywicGx0IjotMX0.s6ZQBPa41YTjVMg0Qv7iCr2am-yM0B2fcsxzN87mZGY; bili_ticket_expires=1778068103; buvid_fp=04be3888d3c017344e3ed2682a3190c5; CURRENT_FNVAL=2000; sid=mrhyll52
      'user-agent': Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

    proxies:
      http:
      https: